site:
  name: まなー2.0
  page_title: まなー2.0 | マナーの本質を考える大喜利サイト
  page_description: 新しいマナーを考えて、この世に蔓延る謎マナーに一石を投じる社会派大喜利サイト、まなー2.0
  page_keywords: マナー
  meta:
    ogp:
      type: website
      image_path: '/images/ogp.png'
